# Configuration de l'application.
# Fichier chargé automatiquement par Spring Boot : @PropertySource est inutile.
spring.datasource.url=jdbc:postgresql://localhost:5432/filmsdb
spring.datasource.username=postgres
spring.datasource.password=azerty
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true